services:
  gitlab:
    image: gitlab/gitlab-ce:18.3.1-ce.0
    container_name: gitlab
    restart: always
    hostname: "gitlab-cnd.example.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-cnd.example.com:8929' # without port if reverse proxy
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - "8929:8929"
      - "443:443"
      - "2424:22"
    volumes:
      - "./gitlab-data/config:/etc/gitlab"
      - "./gitlab-data/logs:/var/log/gitlab"
      - "./gitlab-data/data:/var/opt/gitlab"
    shm_size: "256m"
