version: "3.8"

services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    environment:
      - "HTTP_USER=admin"
      - "HTTP_PASS=admin"
    ports:
      - "53:53/udp"
      - "5380:8080"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    restart: always
    networks:
      - dnsmasq

networks:
  dnsmasq:
